use_frameworks!

platform :ios, '12.0'

target 'HTTPService7Sdk_Example' do
  pod 'HTTPService7Sdk', :path => '../'
  pod 'Common7Sdk', :path => '/Users/mac/Desktop/sdk/localsdk/Common7Sdk/Common7Sdk.podspec'

  target 'HTTPService7Sdk_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
end

